### ISSUE TITLE
Creating PDF from HTML which contains a non-breaking space fails

### ISSUE THREAD

**Issue by jiussanw** [aspose-pdf/Aspose.PDF-for-.NET#17]
When attempting to create a PDF file from HTML text which contains a non-breaking space (i.e. the `&nbsp;` entity) the Aspose.Pdf.Document constructor fails with a `NullReferenceException`.

Code to reproduce:
```csharp
byte[] byteArray = System.Text.Encoding.UTF8.GetBytes("&nbsp;");
using var stream = new System.IO.MemoryStream(byteArray);
var htmloptions = new Aspose.Pdf.HtmlLoadOptions();
var doc = new Aspose.Pdf.Document(stream, htmloptions); // Exception thrown here.
```
The thrown exception:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Aspose.Pdf.Text.Font..ctor(#=zNHBl9bv5dKBFxtt9xgExszk= #=zg4LwFFM=)
   at #=zrqioYeoeEV9SrAkxSuXwlXH5Ifyvlj21WdquE7oNTcGPoqO1Sd3yyi8=.#=zdLqnfTBuN$M4C$2UFip31dB2LdAV(String #=zpnc7MyM=, Font #=zg4LwFFM=, Font& #=zMKyPsWYDEY$fJObf78seVyY=)
   at #=zIQs01lavi4DNdBNklNx6bASPbgzf.#=zuuZIr3uS2Y4E(String #=z_RjUeeI=)
   at Aspose.Pdf.Text.TextFragment.#=zDBWFds67mVyS(String #=z_RjUeeI=)
   at Aspose.Pdf.Text.TextFragment..ctor(String text)
   at #=zvFFs2HgtA62UgDSLh9$2J$vjm0p28ZsJ8g==`1.#=zL7vLnoM=(String #=z_RjUeeI=, PointF #=zj_TlQ5M=)
   at #=z9Li_ajC7P2DH_9gNchZJecBNHI9O.#=z6cQnZaM=(#=zCxY5wubIdFpGMtJOQGw0OHGDaeJIVIRIVQ== #=zcBszi6J1fEZ$, Boolean #=zZdLctoCNtTZ4u74z5g==, #=zJ3vmM7qiKmHn5QQBWTwjvIV8T_SaaenURw== #=zRBCY2gg=)
   at #=z9Li_ajC7P2DH_9gNchZJecBNHI9O.#=zqs1Nsl_OwomM(#=zfWlGV7dhTUFkybysb8upcVwAqi55rK9z0Q== #=zeobQHR4=, Boolean #=zZdLctoCNtTZ4u74z5g==, #=zJ3vmM7qiKmHn5QQBWTwjvIV8T_SaaenURw== #=zRBCY2gg=)
   at #=z9Li_ajC7P2DH_9gNchZJecBNHI9O.#=zE_3gB4gFjgQw$OgACA==(#=zcsJAVB7XAc5g1Y_MdQ== #=z0wYF1JtChsr23LfchQ==, Boolean #=zZdLctoCNtTZ4u74z5g==, #=zJ3vmM7qiKmHn5QQBWTwjvIV8T_SaaenURw== #=zRBCY2gg=)
   at #=z9Li_ajC7P2DH_9gNchZJecBNHI9O.#=zP$TpPEg=(#=zRH8f$IrX5U5FK$jd4WhwBzOLZ0IU4zUhHg== #=zZPNcMZI=, #=z_Ngejrgt9PdYCaBxsQ== #=z0wYF1JtChsr23LfchQ==, Boolean #=zZdLctoCNtTZ4u74z5g==, #=zJ3vmM7qiKmHn5QQBWTwjvIV8T_SaaenURw== #=zRBCY2gg=)
   at #=zArJ$1ei6mH73KsCnFCJHuYXIh2MkH7ERo34xqoQ=.Render(#=zPadphowpHvLcFEFXuH_tOdDwZUYo #=zlu$sVVM=)
   at #=znzoTTXv3NQyq5K0RKul_Ti03pwpiGddQlw==.#=z_1H7pgLZitRn(#=zndSqXilF3Osog0Ga6DxD3V4= #=zuRs8sXEHxAzpoGSFYg==, #=zy00zKi9g6s2rlCYLyH22q3ntVMej[] #=zyUS41KSLWa6j, #=zcR9jE0eKS5zqmNI6sRXeq3ApV$1I #=z0BulzFY=, TimeSpan #=ze$_SWv4=)
   at #=zoJdleXCqLDG06fPZsfiAlUOoZkCB.Render(#=zcR9jE0eKS5zqmNI6sRXeq3ApV$1I #=z0BulzFY=, TimeSpan #=ze$_SWv4=, #=zvn9ALkUwdUVSXZ0I3BOPfIQ=[] #=zbJWDOj8=)
   at #=zE1ve9d8lC0QyRuf_nNrVnr54eeLb.Render(#=zcR9jE0eKS5zqmNI6sRXeq3ApV$1I #=z0BulzFY=, #=zLYSUhy8= #=zOBAXFmY=, TimeSpan #=ze$_SWv4=)
   at #=zE1ve9d8lC0QyRuf_nNrVnr54eeLb.Render(#=zcR9jE0eKS5zqmNI6sRXeq3ApV$1I #=z0BulzFY=, #=zLYSUhy8= #=zOBAXFmY=)
   at #=ziYYDgCOI9XvuTjGmbALJ5m_MmaaU.#=z2LHIfiY=(Stream #=zag2acIWiccKS, Document #=zb50g2w9M2HsL, HtmlLoadOptions #=z8XWl92SxULqa, String #=z8_CisyEchoH1)
   at #=ziYYDgCOI9XvuTjGmbALJ5m_MmaaU.#=z2LHIfiY=(Stream #=zag2acIWiccKS, Document #=zb50g2w9M2HsL, HtmlLoadOptions #=z8XWl92SxULqa)
   at Aspose.Pdf.Document.#=z9jbIOJg=(Stream #=zLhuAIlM=, LoadOptions #=zX_mpQM8=)
   at Aspose.Pdf.Document..ctor(Stream input, LoadOptions options)
```

**Comment by asadalikhan90** [comment]
@jiussanw 

Please try to use Aspose.PDF for .NET 22.5 as we tested using this version and were unable to notice this exception. In case you face any issues, please create a topic in [Aspose.PDF official support forum](https://forum.aspose.com/c/pdf) where it will be addressed accordingly and which is the right place to report issues.
